apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns1-role-binding
  # namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns1-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: pod-reader
