apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns1-role
  namespace: ns1
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  - apps
  - autoscaling
  - batch
  - coordination.k8s.io
  - discovery.k8s.io
  - events.k8s.io
  - networking.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - vpcresources.k8s.aws
  resources: 
  - deployments
  - replicasets
  - daemonsets
  - autoscaling
  - batch
  - statefulsets
  - horizontalpodautoscalers
  - jobs
  - cronjobs
  - controllerrevisions
  - ingresses
  - networkpolicies
  - poddisruptionbudgets
  - rolebindings
  - roles
  - securitygrouppolicies
  - leases
  - endpointslices
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
