apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns1-role
  namespace: ns1
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  - apps
  - autoscaling
  - batch
  resources: 
  - deployments
  - replicasets
  - daemonsets
  - autoscaling
  - batch
  - statefulsets
  - horizontalpodautoscalers
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
