apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns2-role
  namespace: ns2
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
    
