apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns2-role-binding
  namespace: ns2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns2-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: pod-reader

