apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
  name: nginx2
  namespace: ns3
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
