apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader-cluster-role
rules:
- apiGroups: 
  - ""
  resources: ["*"]
  verbs: 
  - get
  - watch
  - list
- apiGroups:
  - extensions
  - apps
  resources: 
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
